services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
      target: testing
      cache_from:
        - type=local,src=/tmp/.buildx-cache
        - type=local,src=/tmp/.cache/go-build
      cache_to:
        - type=local,dest=/tmp/.buildx-cache,mode=max
        - type=local,dest=/tmp/.cache/go-build,mode=max
    environment:
      - GOCACHE=/tmp/.cache/go-build
      - GOPATH=/opt/go
    volumes:
      - ./:/opt/app/